# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# The command for running 'user create' commands: `ansible-playbook -i inventory/hosts setup.yml --tags=create-user-vikunja -e username=USERNAME_HERE -e password=PASSWORD_HERE -e email=EMAIL_ADDRESS_HERE`

- name: Fail if playbook called incorrectly for Vikunja 'user create' command
  ansible.builtin.fail:
    msg: "The `username`, `password`, and `email` variables need to be provided via --extra-vars"
  when: >-
    username is not defined or username == 'USERNAME_HERE' or
    password is not defined or password == 'PASSWORD_HERE' or
    email is not defined or email == 'EMAIL_ADDRESS_HERE'

- name: Set user details for Vikunja
  ansible.builtin.set_fact:
    user:
      username: "{{ username }}"
      initial_email: "{{ email }}"
      initial_password: "{{ password }}"
  no_log: true # hide raw password

- name: Ensure Vikunja service is started
  ansible.builtin.service:
    name: "{{ vikunja_identifier }}"
    state: started
    daemon_reload: true
  register: vikunja_start

- name: Wait a while, so that Vikunja can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: vikunja_start.changed | bool

- name: "Ensure Vikunja user is created - {{ user.username }}"
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/util/ensure_user_registered.yml"
  no_log: true
