# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Vikunja installation tasks
  when: vikunja_enabled | bool
  tags:
    - setup-all
    - setup-vikunja
    - install-all
    - install-vikunja
  block:
    - name: Validate Vikunja configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Vikunja
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Vikunja uninstallation tasks
  when: not vikunja_enabled | bool
  tags:
    - setup-all
    - setup-vikunja
  block:
    - name: Uninstall Vikunja
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
