# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Opengist settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - opengist_uid
    - opengist_gid
    - opengist_hostname
    - opengist_path_prefix
    - opengist_container_network
    - opengist_environment_variables_secret_key

- name: Fail if Opengist database type is invalid
  ansible.builtin.fail:
    msg: >-
      opengist_database_type must be 'mysql', 'postgres', or 'sqlite'.
  when: "opengist_database_type not in ['mysql', 'postgres', 'sqlite']"

- name: Fail if required Opengist + MySQL integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `opengist_database_type` is `mysql`
  when: "opengist_database_type == 'mysql' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - opengist_database_mysql_hostname
    - opengist_database_mysql_password

- name: Fail if required Opengist + Postgres integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `opengist_database_type` is `postgres`
  when: "opengist_database_type == 'postgres' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - opengist_database_postgres_hostname
    - opengist_database_postgres_password

- name: Run if Traefik is enabled
  when: opengist_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Opengist are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - opengist_container_labels_traefik_hostname
        - opengist_container_labels_traefik_path_prefix

    - name: Fail if opengist_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          opengist_container_labels_traefik_path_prefix (`{{ opengist_container_labels_traefik_path_prefix }}`) must be `/`.
          Opengist does not support hosting under a subpath yet.
      when: "opengist_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `opengist_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if opengist_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          opengist_container_labels_traefik_path_prefix (`{{ opengist_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/opengist`).
      when: "opengist_container_labels_traefik_path_prefix != '/' and opengist_container_labels_traefik_path_prefix[-1] == '/'"
