---

roles:
  - src: git+https://github.com/geerlingguy/ansible-role-docker.git
    version: 8.0.0
    name: ansible-role-docker
<<<<<<< Updated upstream
  - src: https://github.com/mother-of-all-self-hosting/ansible-role-postgres
    version: v18.6-2
||||||| Stash base
  - src: https://github.com/mother-of-all-self-hosting/ansible-role-postgres
    version: v18.6-2
=======
  - src: git+https://github.com/mother-of-all-self-hosting/ansible-role-postgres.git
    version: v18.6-2
>>>>>>> Stashed changes
    name: ansible-role-postgres
  - src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
    version: main
    name: com.devture.ansible.role.playbook_help
  - src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
    version: v1.5.0-0
    name: com.devture.ansible.role.systemd_docker_base
collections:
  - name: community.docker
    version: 5.3.0
